### ISSUE TITLE
maxiter in solvers

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp-museum#18]
The solver loops simply terminate when the max amount of iterations is reached. This seems to be undesired. There is an error message that will never be printed, the exception will never be thrown. 

```
double Newton(...)
{
...
    while ((iter < 2 || fabs(fval) > ftol) && iter < maxiter)
    {
...
        if (iter>maxiter)
        {
            errstring= "reached maximum number of iterations";
            throw SolutionError(format("Newton reached maximum number of iterations"));
        }
        iter=iter+1;
    }
    return x;
}
```

The while loop terminates 2 iterations before the exception is thrown. What is the intended behaviour?

**Comment by ibell** [comment]
Hmm.  Ah, maybe it should be iter >= maxiter then.

**Comment by jowr** [comment]
That would still fail. The increment comes after the if-clause, but before the break condition. I'll change it in the code...
