### ISSUE TITLE
Working code in Python of v5

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp-museum#8]
@jowr - check it out!

This is based on SWIG since I can't get xdress+cython working so far on windows:

``` python
import CoolProp

for backend,fluid in [("REFPROP","Ethane&Propane"), ("HEOS","Ethane&Propane")]:
    S = CoolProp.AbstractState_factory(backend, fluid)
    S.set_mole_fractions([0.5,0.5])
    S.update(CoolProp.PT_INPUTS, 1e5, 300)
    print S.rhomolar()
```

**Comment by ibell** [comment]
There are a few warnings for the moment. But the important result is that we can use either backend with this mixture.

**Comment by jowr** [comment]
Great!, I am not in the office today, but I'll have a look as soon as I get back.
